json.extract!(@booking,
              :bl_number,
              :ship_line,
              :origin,
              :destination,
              :vessel,
              :voyage,
              :vessel_eta,
              :watch
)
